/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    id("java")
    id("net.ltgt.errorprone")
    id("net.ltgt.nullaway")
    id("org.sonarqube")
    id("com.diffplug.spotless")
    id("org.gradlex.extra-java-module-info")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:latest.release")
    testImplementation("org.hamcrest:hamcrest:latest.release")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    errorprone("com.google.errorprone:error_prone_core:latest.release")
    errorprone("com.uber.nullaway:nullaway:latest.release")

    compileOnly("com.google.errorprone:error_prone_annotations:latest.release")
    compileOnly("com.uber.nullaway:nullaway-annotations:latest.release")

    implementation("ch.qos.logback:logback-classic:latest.release")
    implementation("com.machinezoo.noexception:noexception:latest.release")
    implementation("org.jspecify:jspecify:latest.release")
}

extraJavaModuleInfo {
    deriveAutomaticModuleNamesFromFileNames = true
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

nullaway {
    annotatedPackages.add("hyphanet.support")
    annotatedPackages.add("hyphanet.key")
}

sonar {
    properties {
        property("sonar.projectKey", "leumor_fred_reloaded")
        property("sonar.organization", "leumor")
        property("sonar.host.url", "https://sonarcloud.io")
    }
}

spotless {
    java {
        importOrder()
        removeUnusedImports()
        // apply a specific flavor of google-java-format
        googleJavaFormat()
        // fix formatting of type annotations
        formatAnnotations()
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
