/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

group = "org.hyphanet"
version = "0.0.1-SNAPSHOT"


dependencies {
    api("org.jspecify:jspecify:latest.release")
}