/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("net.ltgt.gradle:gradle-errorprone-plugin:latest.release")
    implementation("net.ltgt.gradle:gradle-nullaway-plugin:latest.release")
    implementation("org.sonarqube:org.sonarqube.gradle.plugin:latest.release")
    implementation("com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:latest.release")
}